
version: "3.8"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: mrcool10
    #   POSTGRES_DB: somedb
    

  user_app:
    build:
      context: "./"
      dockerfile: dockerfile  # Ensure this matches the actual filename
    environment:
      - DATABASE_URL=postgresql://postgres:mrcool10@postgres:5432/somedb?schema=public

    ports:
      - "3001:3001"
    depends_on:
      - postgres



